config/routes.rb
Rails.application.routes.draw do

  post 'todos/create'
  post 'todos/update'
  root 'projects#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


  def index
    @projects = Project.all
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # POST /todos
  # POST /todos.json
  def update
    Todo.find(params[:commit]).update(isCompleted:params[:isCompleted])
    redirect_to :root
    
  end
  
  def create
    @project = Project.find(params[:selected_project])
    @todo = @project.todos.create(params.require(:todo).permit(:text))

    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App todo-list</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<div class="background">
  <div class="menu">
    <%= content_tag(:h3, "новая задача") %><hr>
    <%= form_with scope: :todos, url: todos_create_path, local: true, id:"create_todo_form" do |form| %>
    <%= text_field(:todo, :text, :placeholder => ' Название задачи...',:class => 'todo_name_input')%>
    <%= select_tag("selected_project", options_from_collection_for_select(@projects, :id, :title, "Категория"), :id => 'selection', :class => 'selection')%>
    <%= link_to('отмена', '#', :id => 'link_close', :class => 'link_close')%>
    <%= link_to('ок', '#', :id => 'link_create', :class => 'link_create')%>
    <%end%>
  </div>
</div>

<div class = "header">
  <%= content_tag(:h1, :Задачи, class: "title") %>
  <%= link_to(image_tag('todoimages/addTodoIcon.png'), '#', :id => 'todo_icon', :class => 'todo_icon')%>
</div>

<div class="container">
	<div class="row">
		<% @projects.each do |project| %>
			<div class=" col-lg-4 col-md-6 col-xs-12 сol-sm-12">
				<div class="projects_block">
          <%= content_tag(:h2, project.title) %><hr>
				  <% project.todos.sort.each do |todo|%>
            <div class="todos">
              <%= form_with scope: :todos, url: todos_update_path, local: true, class: "projects_form" do |form| %>
              <%= check_box_tag(todo.id,  todo.isCompleted)%>
              <%= hidden_field_tag(:isCompleted, !todo.isCompleted)%>
              <%= submit_tag(todo.id, class: "submit", :style => "display: none", id: "submit_"+todo.id.to_s) %>
              <%= content_tag(:label, todo.text, id:"todo_text_"+todo.id.to_s, class: "todo_text", for: todo.id) %>
              <%end%>
            </div>
          <%end%>
				</div>
			</div>
		<%end%>
	</div>
</div>     